# Generated by Django 2.1.2 on 2019-05-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0005_auto_20190502_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=1024),
        ),
    ]
