# Generated by Django 2.1.2 on 2019-05-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0008_auto_20190504_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follow',
        ),
    ]
