# Generated by Django 2.1.2 on 2019-05-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0009_remove_profile_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='tran.Profile'),
        ),
    ]
