# Generated by Django 2.1.2 on 2019-05-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0014_profile_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follow',
        ),
    ]
