# Generated by Django 2.1.2 on 2019-06-08 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0017_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('block', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tran.BookBlock')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='booktag', to='tran.BookTag'),
        ),
    ]
