# Generated by Django 2.1.2 on 2019-06-09 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tran', '0018_auto_20190608_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='booktag',
            name='block',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tran.BookBlock'),
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tran.Book'),
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
