# Generated by Django 2.1.2 on 2019-06-09 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tran', '0019_auto_20190609_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('deathday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('place', models.CharField(blank=True, max_length=128)),
                ('cover', models.CharField(blank=True, max_length=128)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('region', models.CharField(blank=True, max_length=256)),
                ('number', models.IntegerField(blank=True)),
                ('runtime', models.IntegerField(blank=True)),
                ('overview', models.TextField(blank=True, default='')),
                ('cover', models.CharField(blank=True, default='', max_length=256)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ManyToManyField(blank=True, related_name='actor', to='tran.Figure')),
                ('director', models.ManyToManyField(blank=True, related_name='director', to='tran.Figure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('writer', models.ManyToManyField(blank=True, related_name='write', to='tran.Figure')),
            ],
        ),
    ]
