# Generated by Django 2.1.2 on 2019-06-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0021_moviecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktag',
            name='subtitle',
            field=models.CharField(default='', max_length=128),
        ),
    ]
