# Generated by Django 2.1.2 on 2019-06-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0022_booktag_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktag',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(default='', max_length=128),
        ),
    ]
