# Generated by Django 2.1.2 on 2019-06-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0024_auto_20190612_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='media_editor_auth',
            field=models.CharField(blank=True, choices=[('未审核', '未审核'), ('审核中', '审核中'), ('审核通过', '审核通过')], default='未审核', max_length=24),
        ),
    ]
