# Generated by Django 2.2.3 on 2019-07-04 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0027_article_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('block', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tran.MovieBlock')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='movietag', to='tran.MovieTag'),
        ),
    ]
