# Generated by Django 2.2.3 on 2019-07-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0028_auto_20190704_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=128)),
            ],
        ),
    ]
