# Generated by Django 2.2.3 on 2019-07-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0029_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='still',
            field=models.ManyToManyField(blank=True, related_name='still', to='tran.Picture'),
        ),
    ]
