# Generated by Django 2.2.3 on 2019-07-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0030_movie_still'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='play_source',
            field=models.ManyToManyField(blank=True, related_name='play_source', to='tran.Source'),
        ),
    ]
