# Generated by Django 2.2.3 on 2019-07-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0031_auto_20190706_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='plantform',
            field=models.CharField(default='', max_length=128),
        ),
    ]
