# Generated by Django 2.2.3 on 2019-07-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0032_source_plantform'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='originality',
            field=models.CharField(blank=True, choices=[('Y', '原创'), ('N', '非原创')], default='N', max_length=24),
        ),
    ]
