# Generated by Django 2.2.3 on 2019-08-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0033_article_originality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('release_date', models.DateTimeField()),
                ('tab', models.CharField(choices=[('修复BUG', 'fix'), ('增加新功能', 'function'), ('优化功能或显示', 'optimize'), ('修改文案', 'document'), ('重大改动', 'boom'), ('诞生', 'birthday')], max_length=24)),
            ],
        ),
    ]
