# Generated by Django 2.2.3 on 2019-09-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0035_profile_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.CharField(blank=True, default='/cover.png', max_length=100),
        ),
    ]
