# Generated by Django 2.2.3 on 2020-06-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0041_auto_20200612_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='deathday',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='deathday',
        ),
    ]
