# Generated by Django 2.2.3 on 2020-06-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0042_auto_20200612_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='icon',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='icon',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
