# Generated by Django 2.2.3 on 2020-06-13 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tran', '0043_auto_20200612_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='brand',
            field=models.CharField(choices=[('A', 'AMD'), ('I', 'InteI'), ('G', '高通'), ('H', '华为'), ('L', '联发科'), ('W', '未知')], default='W', max_length=12),
        ),
        migrations.AddField(
            model_name='gpu',
            name='brand',
            field=models.CharField(choices=[('A', 'AMD'), ('N', 'NVIDIA'), ('W', '未知')], default='W', max_length=12),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ttm',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.IntegerField(blank=True)),
                ('ttm', models.DateTimeField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('os', models.CharField(choices=[('A', 'Android'), ('I', 'IOS')], max_length=12)),
                ('screen_type', models.CharField(choices=[('1', '刘海屏'), ('2', '挖空屏'), ('3', '全面屏')], max_length=12)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tran.Brand')),
                ('cpu', models.ManyToManyField(blank=True, related_name='pcpu', to='tran.CPU')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tran.Genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Earphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.IntegerField(blank=True)),
                ('ttm', models.DateTimeField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tran.Brand')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tran.Genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
