# Generated by Django 2.2.3 on 2020-06-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0044_auto_20200613_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='earphone',
            name='api',
            field=models.CharField(blank=True, choices=[('有线', '有线'), ('蓝牙', '蓝牙')], max_length=32),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='brand',
            field=models.CharField(blank=True, choices=[('AMD', 'AMD'), ('英特尔', 'InteI'), ('高通', '高通'), ('华为', '华为'), ('联发科技', '联发科'), ('Apple', '苹果')], max_length=12),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='brand',
            field=models.CharField(blank=True, choices=[('AMD', 'AMD'), ('英伟达 NVIDIA', 'NVIDIA')], max_length=12),
        ),
        migrations.AlterField(
            model_name='phone',
            name='os',
            field=models.CharField(blank=True, choices=[('Android', 'Android'), ('IOS', 'IOS')], max_length=12),
        ),
        migrations.AlterField(
            model_name='phone',
            name='screen_type',
            field=models.CharField(blank=True, choices=[('刘海屏', '刘海屏'), ('挖空屏', '挖空屏'), ('全面屏', '全面屏')], max_length=12),
        ),
    ]
